
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 11 11:41:50 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 16;
  public static final int INT = 2;
  public static final int LP = 18;
  public static final int CHAR = 11;
  public static final int SEMI = 4;
  public static final int RP = 19;
  public static final int SWITCH = 10;
  public static final int IF = 15;
  public static final int COMPARATOR = 17;
  public static final int ID = 6;
  public static final int SPACE = 7;
  public static final int STRING = 3;
  public static final int COMMA = 5;
  public static final int FLOAT = 9;
  public static final int EOF = 0;
  public static final int NEWLINE = 12;
  public static final int error = 1;
  public static final int ASSIGN = 14;
  public static final int EOFILE = 8;
  public static final int VAR = 13;
}

